package io.github.nahkd123.pojo.api.item.standard;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import io.github.nahkd123.pojo.api.internal.PojoInternal;
import io.github.nahkd123.pojo.api.item.PojoItem;
import io.github.nahkd123.pojo.api.item.standard.component.Component;
import io.github.nahkd123.pojo.api.item.standard.component.ComponentDataHolder;
import io.github.nahkd123.pojo.api.item.standard.component.ComponentsFactory;
import io.github.nahkd123.pojo.api.item.standard.component.SaveableComponent;
import io.github.nahkd123.pojo.api.registry.UserDefinedId;
import io.github.nahkd123.pojo.api.utils.lore.LoreSorter;

public class StandardPojoItem implements PojoItem {
	private List<UserDefinedId> loreSections;
	private UserDefinedId id;
	private List<Component<?>> components;

	public StandardPojoItem(List<UserDefinedId> loreSections, UserDefinedId id, List<Component<?>> components) {
		this.loreSections = loreSections;
		this.id = id;
		this.components = components;
	}

	public static StandardPojoItem loadFromConfig(List<UserDefinedId> loreSections, UserDefinedId id, ConfigurationSection config) {
		ConfigurationSection componentsConfig = config.getConfigurationSection("components");
		List<Component<?>> components = new ArrayList<>();

		if (componentsConfig != null) {
			for (String name : componentsConfig.getKeys(false)) {
				ConfigurationSection component = componentsConfig.getConfigurationSection(name);
				if (!component.contains("type")) {
					PojoInternal.instance().getPlugin().getLogger()
						.warning("Items: " + id + ": Component '" + name + "' does not have 'type' field");
					continue;
				}

				NamespacedKey type = NamespacedKey.fromString(
					component.getString("type"),
					PojoInternal.instance().getPlugin());

				ComponentsFactory<?> factory = ComponentsFactory.getAllFactories().get(type);
				if (factory == null) {
					PojoInternal.instance().getPlugin().getLogger()
						.warning("Items: " + id + ": Component with type '" + type + "' is not registered!");
					continue;
				}

				Component<?> c = factory.createFromConfig(component);
				components.add(c);
			}
		}

		return new StandardPojoItem(loreSections, id, components);
	}

	public boolean saveToConfig(ConfigurationSection config) {
		ConfigurationSection componentsConfig = config.createSection("components");
		int currentIndex = 0;

		for (Component<?> component : components) {
			if (!(component instanceof SaveableComponent<?> saveable)) return false;
			ConfigurationSection componentConfig = componentsConfig.createSection("Autogenerated Name " + currentIndex);
			componentConfig.set("type", component.getTypeId().toString());
			saveable.saveComponentTo(componentConfig);
			currentIndex++;
		}

		return true;
	}

	@Override
	public UserDefinedId getId() { return id; }

	public List<Component<?>> getComponents() { return components; }

	@SuppressWarnings({ "rawtypes", "unchecked" })
	@Override
	public ItemStack createNew(boolean displayMode) {
		Map<Component<?>, Object> dataMap = new HashMap<>();
		ComponentDataHolder dataHolder = ComponentDataHolder.newHolder();

		// 1. Initialize
		for (Component component : components) {
			Object obj = component.createNewData();
			dataMap.put(component, obj);
			dataHolder.addRaw(component.getClass(), obj);
		}

		// 2. Manipulate
		for (Component component : components) component.applyToOtherComponent(dataMap.get(component), dataHolder);

		// 3. Display
		Material mat = Material.STONE;
		String name = null;
		LoreSorter lore = new LoreSorter(loreSections);

		for (Component component : components) {
			Object obj = dataMap.get(component);
			mat = component.applyMaterial(obj, mat, displayMode);
			name = component.applyName(obj, name, displayMode);
			component.applyLore(obj, lore, displayMode);
		}

		List<String> loreList = lore.build();
		ItemStack stack = new ItemStack(mat);
		ItemMeta meta = stack.getItemMeta();
		PojoItem.super.updateMeta(meta, displayMode);

		if (name != null) meta.setDisplayName(name);
		if (loreList.size() > 0) meta.setLore(loreList);

		// 4. Post display & store data
		for (Component component : components) component.applyPostDisplay(dataMap.get(component), meta, displayMode);

		for (Component component : components) {
			Object obj = dataMap.get(component);
			component.storeDataTo(meta.getPersistentDataContainer(), obj);
		}

		stack.setItemMeta(meta);
		return stack;
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	@Override
	public ItemMeta updateMeta(ItemMeta source, boolean displayMode) {
		source = PojoItem.super.updateMeta(source, displayMode);
		Map<Component<?>, Object> dataMap = new HashMap<>();
		ComponentDataHolder dataHolder = ComponentDataHolder.newHolder();

		// 1. Load
		for (Component component : components) {
			Object obj = component.loadDataFrom(source.getPersistentDataContainer());
			dataMap.put(component, obj);
			dataHolder.addRaw(component.getClass(), obj);
		}

		// 2. Manipulate
		for (Component component : components) component.applyToOtherComponent(dataMap.get(component), dataHolder);

		// 3. Display
		String name = null;
		LoreSorter lore = new LoreSorter(loreSections);

		for (Component component : components) {
			Object obj = dataMap.get(component);
			name = component.applyName(obj, name, displayMode);
			component.applyLore(obj, lore, displayMode);
		}

		List<String> loreList = lore.build();
		if (name != null) source.setLocalizedName(name);
		if (loreList.size() > 0) source.setLore(loreList);

		// 4. Post display (storing data is not included atm)
		for (Component component : components) component.applyPostDisplay(dataMap.get(component), source, displayMode);
		return source;
	}
}
